### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by der-stefan** [geofabrik/tirex#3]
On a completely fresh Ubuntu 16.04 calling the make file throws two errors and exits:

    g++: error: unrecognized command line option ‘-Wtautological-compare’
    g++: error: unrecognized command line option ‘-Wheader-hygiene’

**Comment by der-stefan** [comment]
$ make
    perl Makefile.PL PREFIX=/usr DESTDIR= FIRST_MAKEFILE=Makefile.perl
    Generating a Unix-style Makefile.perl
    Writing Makefile.perl for Tirex
    Writing MYMETA.yml and MYMETA.json
    rm -f Makefile.perl.old
    cd backend-mapnik; make 
    make[1]: Verzeichnis „/home/user/src/tirex/backend-mapnik“ wird betreten
    g++ -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 `mapnik-config --cflags` -Wall -Wextra -pedantic -Wredundant-decls -Wdisabled-optimization -Wctor-dtor-privacy -Wnon-virtual-dtor -Woverloaded-virtual -Wsign-promo -Wold-style-cast   -c -o renderd.o renderd.cc
    g++: error: unrecognized command line option ‘-Wtautological-compare’
    g++: error: unrecognized command line option ‘-Wheader-hygiene’
    <eingebaut>: die Regel für Ziel „renderd.o“ scheiterte
    make[1]: *** [renderd.o] Fehler 1

Again, completely fresh Ubuntu 16.04 LTS with Mapnik compiled and installed before.

**Comment by woodpeck** [comment]
Apparently your mapnik-config generates these additional cflags; the standard mapnik-config that is part of Ubuntu 16.04's libmapnik-dev package doesn't:

    % mapnik-config --cflags|grep tauto
    % root@craig:/# dpkg -l |grep mapnik-dev
    ii  libmapnik-dev                          3.0.9+ds-1                      amd64        C++ toolkit for developing GIS applications (devel)
    %

Use the standard mapnik package or find out why your version generates flags that your c++ cannot understand.

**Comment by der-stefan** [comment]
Thank you very much, @woodpeck. Now it is obvious that Mapnik had the wrong build flags. Luckily the Ubuntu standard package is up-to-date - let's use it instead.
